# ************************************************ #
#     Dockerfile for CGA Production Pipeline       #
# ************************************************ #

# Set the base image to Ubuntu
FROM ubuntu:14.04

# File Author / Maintainer
MAINTAINER lelagina@broadinstitute.org

ENV DEBIAN_FRONTEND noninteractive

# ************************************************ #
#       Update the repository sources list         #
# ************************************************ #

RUN apt-get --yes update \
  && apt-get upgrade --yes \     
  && apt-get install --yes \
  apt-utils \
  aufs-tools \
  automake \
  bc \
  bedtools \
  btrfs-tools \ 
  build-essential \
  cpanminus \
  dpkg-sig \
  expat \
  gcc \
  gcc-multilib \
  gfortran \
  git \
  hdfview \
  imagemagick \
  libatlas-base-dev \  
  libcurl4-openssl-dev \
  libdbd-mysql \
  libdbd-mysql-perl \
  libdbd-pgsql \
  libffi-dev  \
  libfreetype6 \
  libfreetype6-dev \
  libhdf5-dev \ 
  liblzma-dev \
  libmysqlclient-dev \
  libncurses-dev \
  libopenmpi-dev \
  libopenmpi1.6 \
  libpng-dev \
  libreadline-dev \  
  libstdc++6 \
  libx11-dev \
  libxft-dev \  
  libXp-dev \
  libxpm-dev \
  lynx \
  make \
  openbox \  
  openmpi-bin \
  openmpi-common \
  openssh-client \
  openssh-server \ 
  python \
  python-dev \
  python-pip \  
  python-setuptools \
  python-software-properties \
  python3-pip \ 
  software-properties-common \
  sudo \
  tabix \
  tcl \
  tcl-dev \
  tk \
  tk-dev \ 
  unzip \
  xorg \
  xorg-dev \ 
  zip \
  zlib1g-dev \
  libbz2-dev 
  #python-bzutils  

# ************************************************ #
#               PIP Install                        #
# ************************************************ #

RUN pip install -U pip 
RUN pip install virtualenv numpy scipy pysam cython  
RUN pip install -U --ignore-installed six setuptools sklearn matplotlib scimath 
RUN pip install h5py pandas ArgumentParser lxml 

ENV SAMTOOLS_INSTALL_DIR=/opt/samtools

COPY htslib-1.6.tar.bz2 /opt/
RUN cd /opt \
    && tar -xf htslib-1.6.tar.bz2 \
    && rm htslib-1.6.tar.bz2 \
    && cd htslib-1.6 \
    && make \
    && make install \
    && make clean

#WORKDIR /tmp
#RUN wget https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2 && \
#  tar --bzip2 -xf samtools-1.3.1.tar.bz2

#WORKDIR /tmp/samtools-1.3.1
#RUN ./configure --enable-plugins --prefix=$SAMTOOLS_INSTALL_DIR && \
##  make all all-htslib && \
#  make install install-htslib

#WORKDIR /
#RUN ln -s $SAMTOOLS_INSTALL_DIR/bin/samtools /usr/bin/samtools && \
#  rm -rf /tmp/samtools-1.3.1

# samtools
COPY samtools-1.6.tar.bz2 /opt/
RUN cd /opt \
    && tar -xf samtools-1.6.tar.bz2 \
    && rm samtools-1.6.tar.bz2 \
    && cd samtools-1.6 \
    && ./configure --with-htslib=/opt/htslib-1.6 \
    && make \
    && make install \
    && make clean

COPY blat-realigner/ /opt/blat-realigner/
RUN cd /opt/blat-realigner/SeqLib \
  && make clean \
  && make

RUN cd /opt/blat-realigner/src \
  && python setup.py install

RUN ln -sFv /opt/blat-realigner/src/realign.py /opt/realign.py

# You are missing this file (find attached to email)
COPY hg19.11.ooc /opt/ 

# Error is here
RUN pip install twobitreader

COPY realignmentReads.py /opt/realignmentReads.py